
-- Insert the new AI tools into the ai_tools table with properly escaped quotes
INSERT INTO public.ai_tools (
  name, logo, description, shortdescription, category, pricing, rating, reviewcount, features, url, apiaccess, createdat, pros, cons, usecases
) VALUES 
(
  'Den',
  'https://example.com/den-logo.png',
  'Den is a collaborative AI agent workspace where humans and agents work together in real time across chats, documents, and automation. With 50+ integrations, Den allows agents to interact with your tools like Slack, Supabase, Notion, and more. Its core strength lies in enabling multi-agent workflows tailored to your business context.',
  'Multiplayer AI agent workspace with 50+ app integrations.',
  ARRAY['AI Agents', 'Collaboration', 'Automation'],
  'Freemium',
  4.6,
  100,
  ARRAY['50+ app integrations', 'real-time collaboration', 'agent swarms', 'knowledge understanding', 'task automation'],
  'https://www.den.ai',
  true,
  '2025-06-19T08:36:34.463683+00',
  ARRAY['User-friendly interface', 'supports automation across tools', 'powerful AI agents'],
  ARRAY['Still developing advanced customizations', 'enterprise use may need setup'],
  ARRAY['Internal team collaboration', 'agent-powered workflows', 'automated document handling']
),
(
  'DeckSpeed',
  'https://example.com/deckspeed-logo.png',
  'DeckSpeed is a revolutionary presentation tool that transforms your spoken ideas into fully designed, professional presentations. Unlike template-bound tools, DeckSpeed provides real-time conversational slide generation, powerful charting, and stunning visuals with full creative control.',
  'AI slide creator that builds presentations from conversation.',
  ARRAY['Presentation', 'Productivity', 'Business'],
  'Freemium',
  4.7,
  90,
  ARRAY['3D model slides', 'personalized styling', 'real-time editing', 'one-click charts'],
  'https://www.deckspeed.ai',
  false,
  '2025-06-19T08:36:34.463696+00',
  ARRAY['No templates needed', 'high design quality', 'responsive to user feedback'],
  ARRAY['Not ideal for rigid corporate templates'],
  ARRAY['Sales presentations', 'startup pitches', 'educational content']
),
(
  'Kolbo.AI',
  'https://example.com/kolboai-logo.png',
  'Kolbo.AI combines all major AI models like ChatGPT, Claude, Gemini, Midjourney and others into a unified subscription-based platform. It enables multi-model chat, team collaboration, advanced media management, and AI-powered project workflows.',
  'One platform for all major AI models with team tools.',
  ARRAY['Conversational AI', 'Collaboration', 'Business'],
  'Freemium',
  4.8,
  120,
  ARRAY['Multi-model chat', 'media hub', 'real-time collaboration', 'magic notebook'],
  'https://www.kolbo.ai',
  false,
  '2025-06-19T08:36:34.463701+00',
  ARRAY['Cost-effective', 'all-in-one model access', 'team collaboration'],
  ARRAY['Limited features in free plan', 'occasional model inconsistencies'],
  ARRAY['AI experimentation', 'creative media projects', 'model benchmarking']
),
(
  'Yazo',
  'https://example.com/yazo-logo.png',
  'Yazo is a comprehensive content marketing platform powered by AI. It allows users to generate SEO-optimized articles, perform keyword research, analyze competitors, and organize their content workflows in one place.',
  'AI-driven SEO content and keyword planning platform.',
  ARRAY['Content Creation', 'Marketing', 'Text Generation'],
  'Freemium',
  4.7,
  95,
  ARRAY['AI article writing', 'keyword planner', 'competitor analysis', 'SEO optimization'],
  'https://www.yazo.ai',
  false,
  '2025-06-19T08:36:34.463706+00',
  ARRAY['SEO-focused tools', 'multilingual support', 'easy WordPress integration'],
  ARRAY['UI can be overwhelming for beginners'],
  ARRAY['Blog content writing', 'SEO strategy building', 'content planning']
),
(
  'LinkRobot',
  'https://example.com/linkrobot-logo.png',
  'LinkRobot automates the internal linking process using AI. It crawls websites, suggests keyword anchors, finds linking opportunities, and integrates directly with WordPress for one-click implementation.',
  'AI-powered internal linking for SEO automation.',
  ARRAY['Marketing', 'Automation'],
  'Freemium',
  4.5,
  80,
  ARRAY['Internal link automation', 'keyword anchors', 'WordPress integration'],
  'https://www.linkrobot.ai',
  false,
  '2025-06-19T08:36:34.463710+00',
  ARRAY['Simple automated SEO improvement', 'no manual effort required'],
  ARRAY['Primarily WordPress-focused', 'less flexible for custom CMS'],
  ARRAY['SEO optimization', 'content linking', 'blog post enhancement']
),
(
  'Krea',
  'https://example.com/krea-logo.png',
  'Krea is an advanced AI-powered design tool for creating hyper-realistic images and videos. With its Krea 1 model, users can control aesthetics using style reference images and produce consistent, beautiful outputs.',
  'AI design platform with style-guided generation.',
  ARRAY['Image Generation', 'Video Editing', 'Design'],
  'Freemium',
  4.6,
  85,
  ARRAY['Image & video generation', 'style reference system', 'high realism'],
  'https://www.krea.ai',
  false,
  '2025-06-19T08:36:34.463714+00',
  ARRAY['High-quality visuals', 'artistic control', 'beta access'],
  ARRAY['Access is limited', 'early-stage model availability'],
  ARRAY['Creative visuals', 'digital art', 'design prototyping']
),
(
  'PaperCheck',
  'https://imgur.com/a/98i9J5t',
  'PaperCheck is an AI-powered proofreading service designed to help students improve the quality of their academic papers including Theses, Research Papers and Dissertation quickly and affordably. Offering instant and detailed feedback on structure, clarity, and content, PaperCheck empowers students and researchers to refine their work with precision. Beyond basic proofreading, PaperCheck includes features such as task planning to help manage remaining steps in the writing process, ensuring students stay on track. The platform also offers a unique defense preparation tool, which generates potential defense questions and allows students to practice their responses, receiving constructive feedback to boost confidence. With specialized models tailored for academic writing, PaperCheck AI delivers targeted and in-depth analysis, far exceeding what general tools provide. It highlights areas for improvement without rewriting content, encouraging students to strengthen their own work. Available at a fraction of the cost of traditional proofreading services, PaperCheck makes high-quality academic feedback accessible to all, helping students reach their full potential.',
  'PaperCheck is an AI-powered tool that helps students polish theses, research papers, and dissertations with instant feedback, task planning, and defense prep all at an affordable price.',
  ARRAY['Education', 'Text Generation'],
  'Paid',
  4.5,
  75,
  ARRAY['Academic proofreading', 'task planning', 'defense preparation', 'structure analysis', 'content feedback'],
  'https://papercheck.ai',
  false,
  '2025-06-16T11:25:04.406525+00',
  ARRAY['Specialized for academic writing', 'affordable pricing', 'comprehensive feedback', 'defense preparation'],
  ARRAY['Limited to academic content', 'may require manual review for complex papers'],
  ARRAY['Academic paper proofreading', 'thesis improvement', 'research paper editing', 'dissertation preparation']
),
(
  'HypeDesk',
  'https://hypedesk.io/web-app-manifest-512x512.png',
  'HypeDesk is an all-in-one, AI-powered marketing platform designed for indie developers, solo founders, and early-stage startups to boost productivity and automate growth without a marketing budget. Leveraging artificial intelligence and machine learning, HypeDesk generates on-brand marketing content, automates lead generation and personalized outreach, and manages all your materials in a centralized hub. Promote your project in 400+ curated directories, communities, and platforms, build powerful backlinks for domain authority, and schedule AI-generated social posts in seconds. The Chrome Extension autofills forms and generates content anywhere, making marketing seamless and efficient. HypeDesk empowers you to find your first 100 clients and grow your project using free, AI-driven tactics eliminating the need for expensive tools, agencies, or manual work. Whether you are launching, growing, or just trying to get noticed, HypeDesk gives you everything you need to market smarter, automate outreach, and maximize productivity with artificial intelligence.',
  'Promote your startup with AI and zero budget. HypeDesk helps you generate marketing materials, manage leads, and access 400+ promotion places effortlessly.',
  ARRAY['Marketing', 'Automation', 'Business'],
  'Freemium',
  4.6,
  85,
  ARRAY['AI marketing content', 'lead generation', 'directory submissions', 'social media automation', 'Chrome extension', 'backlink building'],
  'https://hypedesk.io',
  false,
  '2025-06-16T17:52:03.131924+00',
  ARRAY['Zero marketing budget needed', 'comprehensive marketing suite', 'automation features', '400+ promotion platforms'],
  ARRAY['May require setup time', 'learning curve for advanced features'],
  ARRAY['Startup marketing', 'indie developer promotion', 'lead generation', 'social media management']
),
(
  'Capalyze',
  'https://release-univer.oss-cn-shenzhen.aliyuncs.com/template-resource/QS6tfBwxOdHCebZb7E7w8_capalyze-ai-logo.png',
  'Capalyze is a leading data analytics agent built for individuals and businesses. It supports linking multiple data sources and crawling network data, describing analysis needs, and presenting intelligent insights, helping e-commerce operations, real estate sales, self-media operations, and local life merchants extract valuable information from massive data and empower business decisions. Data analysis, as easy as a conversation - No learning curve, simply ask in natural language. Capalyze understands your intent, analyzes your data, and generates insights automatically. Turn complex data into clear answers, just like chatting. AI-powered data insights, tailored to your needs - Built-in analysis modes and machine learning algorithms intelligently select the right models for your goals whether its sales forecasting, user behavior analysis, or financial cost breakdowns. Unlock accurate, actionable insights with ease.',
  'Capalyze is the only AI that lets you capture web data across platforms, run sentiment analysis, and automate it all through natural language.',
  ARRAY['Data Analysis', 'Business', 'Automation'],
  'Freemium',
  4.7,
  95,
  ARRAY['Natural language queries', 'multi-source data integration', 'web data crawling', 'sentiment analysis', 'interactive dashboards', 'spreadsheet editing'],
  'https://capalyze.ai/',
  false,
  '2025-06-18T04:22:17.208182+00',
  ARRAY['Natural language interface', 'comprehensive data integration', 'web crawling capabilities', 'interactive reporting'],
  ARRAY['Learning curve for advanced features', 'may require data cleaning'],
  ARRAY['E-commerce analysis', 'real estate data insights', 'social media analytics', 'market research']
),
(
  'AI Text Humanizer',
  'https://example.com/ai-text-humanizer-logo.png',
  'An AI text humanizer transforms AI-generated content into natural, human-like text. It adds flow, uses conversational phrasing, and avoids robotic language. Our humanization tool helps create engaging and authentic-sounding material for various content needs.',
  'Free AI Text Humanizer',
  ARRAY['Text Generation', 'Content Creation'],
  'Free',
  4.3,
  65,
  ARRAY['Text humanization', 'conversational phrasing', 'flow improvement', 'robotic language detection'],
  'https://www.aitexthumanizer.app/',
  false,
  '2025-06-18T08:35:33.114562+00',
  ARRAY['Free to use', 'improves AI text quality', 'easy to use interface'],
  ARRAY['Limited advanced features', 'may require manual review'],
  ARRAY['Content improvement', 'AI text enhancement', 'blog post humanization']
),
(
  'X-Ray Contact',
  'https://example.com/x-ray-contact-logo.png',
  'X-Ray Contact is a powerful identity verification platform. It helps professionals quickly find and verify email addresses, phone numbers, usernames, and other digital footprints. X-Ray Contact supports due diligence, OSINT investigations, and fraud prevention. It is widely used by recruiters, investigators, analysts, and compliance teams who need reliable, fast, and comprehensive results.',
  'X-Ray Contact is all-in-one platform to verify identities automatically.',
  ARRAY['Data Analysis', 'Business'],
  'Paid',
  4.4,
  70,
  ARRAY['Identity verification', 'email validation', 'phone number lookup', 'OSINT investigations', 'fraud prevention', 'digital footprint analysis'],
  'https://x-ray.contact/',
  false,
  '2025-06-18T11:34:22.614862+00',
  ARRAY['Comprehensive verification', 'fast results', 'professional grade', 'multiple data sources'],
  ARRAY['Paid service only', 'privacy considerations', 'requires responsible use'],
  ARRAY['Due diligence', 'recruitment verification', 'fraud investigation', 'compliance checks']
);
