
-- Insert the new SEO and content creation tools into the ai_tools table
INSERT INTO public.ai_tools (
  id, name, logo, description, shortdescription, category, pricing, rating, reviewcount, features, url, apiaccess, createdat, pros, cons, usecases
) VALUES 
(
  '140a3514-6d43-45cf-b20e-d167865ff589',
  'ClickUp',
  'https://clickup.com/blog/wp-content/uploads/2023/07/ClickUp-logo.png',
  'ClickUp AI combines SEO-centric content tools with project management capabilities. It includes SEO prompts, keyword research, summarization, and optimization tools within a collaborative platform.',
  'SEO content creation + project management with AI prompts.',
  ARRAY['SEO', 'Content Marketing', 'Project Management'],
  'Free to $12/user/month + $5 AI add-on',
  4.7,
  6800,
  ARRAY['SEO prompts', 'Content optimization', 'Keyword research', 'Project collaboration', 'Summarization'],
  'https://clickup.com',
  false,
  '2025-06-21T17:38:22.602836+00',
  ARRAY['Integrated project management', 'SEO-aware content generation', 'Wide template support'],
  ARRAY['Limited search tracking', 'Needs other tools for full SEO audits'],
  ARRAY['Write optimized blogs', 'Team collaboration on content', 'Plan SEO campaigns']
),
(
  '13f87e36-f809-4fa9-b300-71f6f4f3afc7',
  'Surfer SEO',
  'https://surferseo.com/images/logo.svg',
  'Surfer SEO is a content intelligence platform offering AI tools for optimizing content strategy, outline generation, and keyword placement to grow organic traffic.',
  'Content intelligence and on-page SEO optimization tool.',
  ARRAY['SEO', 'Content Optimization'],
  '$29–$299/month',
  4.8,
  450,
  ARRAY['SERP Analyzer', 'Content editor', 'Keyword research', 'AI outline generation'],
  'https://surferseo.com',
  false,
  '2025-06-21T17:38:22.602929+00',
  ARRAY['Strong SEO features', 'AI task generator', 'Integrated strategy tools'],
  ARRAY['Steep learning curve', 'Limited collaboration tools'],
  ARRAY['Optimize existing blogs', 'Build outlines for new SEO content', 'Research keyword density']
),
(
  '9aede0a3-4fcd-4011-9579-7170b9a95c92',
  'WordLift',
  'https://wordlift.io/wp-content/themes/wordlift/images/logo.svg',
  'WordLift is an AI SEO tool focused on structured data generation for better search engine rankings. It uses AI to create custom knowledge graphs and metadata to improve content discoverability.',
  'Structured data generation and content metadata enhancement.',
  ARRAY['SEO', 'Structured Data', 'E-commerce'],
  '~$63–$266/month',
  4.8,
  30,
  ARRAY['Knowledge graphs', 'Structured data markup', 'Content suggestions', 'E-commerce optimization'],
  'https://wordlift.io',
  false,
  '2025-06-21T17:40:01.690621+00',
  ARRAY['Improves search appearance', 'Built on multiple AI platforms', 'Great for schema markup'],
  ARRAY['Limited writing tools', 'Complex setup for large sites'],
  ARRAY['Improve e-commerce visibility', 'Add structured data', 'Enhance search presence']
),
(
  '5291b22e-a345-4c66-9fb7-d9479b22f5a6',
  'Jasper',
  'https://www.jasper.ai/images/logo.svg',
  'Jasper is an AI-powered content creation tool designed for marketers. It helps teams generate brand-aligned content optimized for SEO using templates and natural language processing.',
  'AI writing assistant with SEO and brand voice alignment.',
  ARRAY['Content Creation', 'SEO', 'Marketing'],
  '$49–$125+/month',
  4.7,
  1200,
  ARRAY['Brand voice training', 'SEO templates', 'Language support', 'AI copywriting'],
  'https://www.jasper.ai',
  false,
  '2025-06-21T17:40:01.690769+00',
  ARRAY['Great for brand voice', 'SEO template integration', 'Supports long-form content'],
  ARRAY['Needs Surfer SEO for optimization', 'No plagiarism checker'],
  ARRAY['Write SEO blogs', 'Create ad copy', 'Generate landing page content']
),
(
  'caf4ab90-2025-47c6-8f87-c3c1975f894e',
  'NitroPack',
  'https://nitropack.io/images/logo.svg',
  'NitroPack improves SEO by increasing website speed. It offers caching, image optimization, and performance enhancements for HTML, CSS, and JavaScript.',
  'Website speed optimization for SEO improvement.',
  ARRAY['Site Speed', 'SEO'],
  '$21–$176/month',
  4.5,
  100,
  ARRAY['Caching', 'WebP conversion', 'Performance tools', 'CDN integration'],
  'https://nitropack.io',
  false,
  '2025-06-21T17:40:01.690864+00',
  ARRAY['Improves load speed', 'Easy WordPress integration'],
  ARRAY['Limited CMS support', 'Not full SEO solution'],
  ARRAY['Speed up website', 'Improve Core Web Vitals', 'Reduce bounce rate']
),
(
  'e1db345b-6e0b-4b78-8e71-ee4eb7eca1f9',
  'Alli AI',
  'https://www.alliai.com/wp-content/uploads/2020/12/alliAI-logo.png',
  'Alli AI is an SEO automation tool for large websites. It allows real-time SEO changes, content editing, and A/B testing of meta tags directly on live pages.',
  'Real-time SEO automation and on-page editing.',
  ARRAY['SEO Automation'],
  '$249–$999+/month',
  4.3,
  10,
  ARRAY['Real-time deployment', 'A/B testing', 'Auto title generation', 'Content editor'],
  'https://www.alliai.com',
  false,
  '2025-06-21T17:40:01.690943+00',
  ARRAY['Auto-deploy changes', 'Includes speed optimization'],
  ARRAY['Can overwhelm with suggestions', 'Lacks keyword research'],
  ARRAY['Optimize large sites', 'Automate SEO fixes', 'Test titles and descriptions']
),
(
  'df584642-2104-46ad-b9c6-e1c175e280dd',
  'Byword',
  'https://www.byword.ai/assets/logo.svg',
  'Byword generates SEO articles using target keywords and writing style preferences. It supports bulk generation and bypasses many AI content detectors.',
  'Bulk SEO article generation using AI.',
  ARRAY['AI Writing', 'SEO'],
  '$99–$2499/month',
  4.6,
  150,
  ARRAY['Bulk article generation', 'Style definition', 'AI detection avoidance', 'Multilingual support'],
  'https://www.byword.ai',
  false,
  '2025-06-21T17:40:01.691007+00',
  ARRAY['Fast content creation', 'High-quality AI outputs'],
  ARRAY['High cost per article', 'No SEO tools beyond writing'],
  ARRAY['Write long-form SEO content', 'Scale niche blogs', 'Multilingual site content']
),
(
  '064996f4-4e4c-47bf-8f7f-ed13595b23d0',
  'MarketMuse',
  'https://marketmuse.com/wp-content/uploads/2021/10/marketmuse-logo.svg',
  'MarketMuse is a content intelligence platform that helps plan, optimize, and audit content strategies through SERP analysis and content clustering.',
  'Content planning and optimization with AI.',
  ARRAY['Content Strategy', 'SEO'],
  '$0–$399+/month',
  4.6,
  200,
  ARRAY['Content briefs', 'SERP analysis', 'Content clusters', 'Optimization tools'],
  'https://www.marketmuse.com',
  false,
  '2025-06-21T17:40:01.691071+00',
  ARRAY['Content audit & planning', 'Cluster-level insights'],
  ARRAY['Steep learning curve', 'Basic editor'],
  ARRAY['Audit existing content', 'Plan content calendar', 'Analyze competitor coverage']
),
(
  'dea1b6ca-8b35-4ef3-97cc-9cd8fc8f88da',
  'Frase',
  'https://www.frase.io/img/frase-logo-dark.svg',
  'Frase helps create, optimize, and analyze SEO content using AI. It includes brief creation, content scoring, and competitor analysis tools.',
  'AI-powered content briefs and SEO analysis.',
  ARRAY['SEO', 'Content Creation'],
  '$14.99–$114.99/month',
  4.9,
  275,
  ARRAY['Brief creation', 'Content scoring', 'Competitor analysis', 'AI templates'],
  'https://www.frase.io',
  false,
  '2025-06-21T17:40:01.691158+00',
  ARRAY['Easy UI', 'Strong generation templates'],
  ARRAY['Weak keyword research', 'No CMS integration'],
  ARRAY['Generate briefs', 'Write & optimize SEO blogs', 'Analyze top competitors']
),
(
  'a4a5438f-2027-49df-a03c-06a7c545449c',
  'WriterZen',
  'https://writerzen.net/logo.svg',
  'WriterZen is an SEO-focused content creation suite with keyword research, topic clustering, AI-assisted writing, and plagiarism detection.',
  'SEO writing suite with keyword & topic tools.',
  ARRAY['SEO', 'Content Writing'],
  '$23–$399/month',
  4.8,
  200,
  ARRAY['Keyword explorer', 'Topic cluster', 'Content editor', 'Team collaboration'],
  'https://writerzen.net',
  false,
  '2025-06-21T17:40:01.691231+00',
  ARRAY['Keyword-rich writing', 'Great for teams'],
  ARRAY['Cluttered UI', 'Lacks backlink tools'],
  ARRAY['Create SEO blog plans', 'Research keywords', 'Write optimized content']
);
